### ISSUE TITLE
vitest not work - "( Vitest should be configured to be able to run from project root )"

### ISSUE THREAD

**Issue by mengqianyixing** [vitest-dev/vitest-explorer#15]
![image](https://user-images.githubusercontent.com/70135517/162660924-7a9d3269-622c-4363-9694-d322183ec9af.png)

**Comment by Aaron-Pool** [comment]
@mengqianyixing 

I got this when I first tried to use the extension as well. The solution for me was to use the following setting to have my package manager run the test instead of whatever the extension was trying to do to locate the correct command:

![image](https://user-images.githubusercontent.com/5634834/163435316-5992b009-a163-43ab-9ae1-1248af5f5a5e.png)

In my case, `pnpm vitest` was the correct setting. But yours may be different, depending on the package manager you're using and what it's cli is for using installed binaries.

**Comment by xon52** [comment]
`pnpm` didn't help; I'm still having this error.

**Comment by mengqianyixing** [comment]
> @mengqianyixing
> 
> I got this when I first tried to use the extension as well. The solution for me was to use the following setting to have my package manager run the test instead of whatever the extension was trying to do to locate the correct command:
> 
> ![image](https://user-images.githubusercontent.com/5634834/163435316-5992b009-a163-43ab-9ae1-1248af5f5a5e.png)
> 
> In my case, `pnpm vitest` was the correct setting. But yours may be different, depending on the package manager you're using and what it's cli is for using installed binaries.

it's still not work by use 'pnpm vitest', look like the "vitest" it's not good support for the windows. :)

**Comment by Aaron-Pool** [comment]
> > @mengqianyixing
> > I got this when I first tried to use the extension as well. The solution for me was to use the following setting to have my package manager run the test instead of whatever the extension was trying to do to locate the correct command:
> > ![image](https://user-images.githubusercontent.com/5634834/163435316-5992b009-a163-43ab-9ae1-1248af5f5a5e.png)
> > In my case, `pnpm vitest` was the correct setting. But yours may be different, depending on the package manager you're using and what it's cli is for using installed binaries.
> 
> it's still not work by use 'pnpm vitest', look like the "vitest" it's not good support for the windows. :)

For what it's worth, I'm on windows as well. And it's working for me. So I'm guessing windows isn't the root of your problem.

**Comment by zxch3n** [comment]
@mengqianyixing Is this still happening on v0.1.17?

**Comment by AlmarAubel** [comment]
We still have the problem in v0.1.17

**Comment by zxch3n** [comment]
@AlmarAubel Is your env.PATH equal to `undefined` as well? If so, how about setting vitest.nodeEnv to `{PATH: "/path/to/node"}`

**Comment by AlmarAubel** [comment]
![image](https://user-images.githubusercontent.com/14359811/163978394-f24bf8c5-308c-4c09-917c-8fff56958964.png)
yes env.PATH: undefined

Tried to set vitest.nodeEnv to    "vitest.nodeEnv": {"PATH":"C:\\Program Files\\nodejs\\"       }. But keep having the same error.
When i debug a test I get this error:
```
Some breakpoints might not work in your version of Node.js. We recommend upgrading for the latest bug, performance, and security fixes. Details: [https://aka.ms/AAcsvqm]()
"[C:\Program]() Files\nodejs\node.exe" [.\node_modules\vitest\vitest.mjs]() run /source/xxxxx/AdresField.test.ts --testNamePattern "Adressfield should render" --reporter=default --reporter=json --outputFile [C:\Users\Almar\AppData\Local\Temp\vitest-report-4m0912.json]()
 RUN  v0.9.3 [c:/source/xxxx]()
node_modules/vitest/dist/chunk-vite-node-externalize.9aaddc2d.js:13008
```
Could not read source map for [file:///c:/source/xxxxx/@vite/env](): ENOENT: no such file or directory, open '[c:\source\xxxx\]()@vite\env.mjs.map'

**Comment by zxch3n** [comment]
@AlmarAubel Can you try "vitest.nodeEnv": {"PATH":"C:\\Program Files\\nodejs\\" }

**Comment by AlmarAubel** [comment]
Same error.
Just tried to debug the extension 
The scheduleRun is called with the following arguments it's looks like the vitestCommand is not correct.
![image](https://user-images.githubusercontent.com/14359811/163992375-8ea3bffd-7665-4842-bb97-93b6c2b12de9.png)
i'm not sure if i understand the code correctly. But the getVitestPath always returns de mjs path. Maybe the code should be changed to:
Also changed the order of the suffixes
![image](https://user-images.githubusercontent.com/14359811/163992658-c6db7e39-c16d-4a7c-ba2c-30b24b6a5420.png)

**Comment by zxch3n** [comment]
Thanks! @AlmarAubel

**Comment by zxch3n** [comment]
Is this still happening on v0.1.18? @mengqianyixing @xon52

**Comment by xon52** [comment]
@zxch3n same error with additional lines in blue:
![image](https://user-images.githubusercontent.com/30713944/164712818-c2153aec-ee0b-4392-90d7-0eb2d848fd3a.png)

**Comment by zxch3n** [comment]
@xon52 this looks like another issue. Do you use a dynamic test name or `it.each` in `AnimatedLetter.test.ts`?

Have you met the error with `Vitest should be configured to be able to run from project root`?

**Comment by xon52** [comment]
I get this for all my tests, and no, nothing fancy at all. This has never worked, even boilerplate.

If I run `vitest` from the normal script method in the terminal it works fine.

**Comment by zxch3n** [comment]
@xon52 If you run the test with the plugin, would you see an error like this one?
![image](https://user-images.githubusercontent.com/18425020/164716536-9aec8a84-36e6-4085-845f-5907d86d57ae.png)

**Comment by xon52** [comment]
All green from terminal/script method:
![image](https://user-images.githubusercontent.com/30713944/164718050-71fab3aa-f727-4f97-a3a6-591f4e8c58e1.png)

Exact same error as before:
![image](https://user-images.githubusercontent.com/30713944/164718477-5ab492a0-c23b-42e7-8328-dff0f50e5592.png)

**Comment by zxch3n** [comment]
The source map error can be safely ignored. Sorry, but I don't know why it cannot find the test suite. I cannot reproduce this error on my Windows machine. If you're interested, contributions are welcome

**Comment by xon52** [comment]
@mengqianyixing @zxch3n are either of you using `nvm`?
I am and I wonder if that's at all a contributor?

**Comment by zxch3n** [comment]
@AlmarAubel Hi, can you debug successfully? I wonder whether you have met the same problem.

@xon52 yes, I use nvm. But I'm not sure what's the course of debugging result not found error. 

> I am and I wonder if that's at all a contributor?

Sorry, I don't know what you mean here

**Comment by xon52** [comment]
Oh ok. I was wondering if there was something strange with the Node path because of nvm.

And I meant cause contributor not GitHub contributor 😅 Sorry! I will try explore more later. Do you use Discord? I couldn't find you. Add me on there if you want to chat more easily about this: xon52#5557

**Comment by AlmarAubel** [comment]
I believe my PR will fix this issue (at least at my machine ;)) @zxch3n  can you verify that it's also working on your machine?

**Comment by AlmarAubel** [comment]
@xon52 could you check should be fixed in v0.1.18

**Comment by xon52** [comment]
@AlmarAubel still not working for me. I did fix normal Run mode with this Draft PR: #24 
But I haven't finished on the Debug mode.

Please could you pull and test if it works on your machine?

**Comment by AlmarAubel** [comment]
Did you still have de node env setting set in your workspace settings?

**Comment by xon52** [comment]
No I don't have any vitest settings in my workspace.

**Comment by hhsl** [comment]
Hey, I experienced `"( Vitest should be configured to be able to run from project root )"` on macOS as well. What helped in my case was running VSCode from the project root (`code .`). For example running VSCode from an app launcher provokes the error again.

Maybe this helps :)

**Comment by darkgrayknight** [comment]
I am also getting this error in debug, though it passes, the test keeps running and doesn't complete. If I get it to stop, it shows it passed.

`
"C:\Program Files\WindowsPowerShell\Modules\nvm\2.5.1\vs\v16.14.2\node.exe" .\node_modules\vitest\vitest.mjs run tests/Basic.spec.tsx --testNamePattern "Test Basic" --reporter=default --reporter=json --outputFile C:/Users/USER/AppData/Local/Temp/vitest-report-hpuz2.json
 RUN  v0.9.3 c:/Users/USER/source/repos/REPO
node_modules/vitest/dist/chunk-vite-node-externalize.9aaddc2d.js:13008
Could not read source map for file:///c:/Users/USER/source/repos/REPO/@vite/env: ENOENT: no such file or directory, open 'c:\Users\USER\source\repos\REPO\@vite\env.mjs.map'
 √ tests/input/Basic.spec.tsx  (15 tests | 14 skipped) 615ms
node_modules/vitest/dist/chunk-vite-node-externalize.9aaddc2d.js:13008
Test Files  1 passed (1)
node_modules/vitest/dist/chunk-vite-node-externalize.9aaddc2d.js:13008
     Tests  1 passed | 14 skipped (15)
node_modules/vitest/dist/chunk-vite-node-externalize.9aaddc2d.js:13008
      Time  27.05s (in thread 615ms, 4398.58%)
node_modules/vitest/dist/chunk-vite-node-externalize.9aaddc2d.js:13008
JSON report written to C:/Users/USER/AppData/Local/Temp/vitest-report-hpuz2.json
node_modules/vitest/dist/chunk-vite-node-externalize.9aaddc2d.js:13008
close timed out after 1000ms
`

**Comment by itpropro** [comment]
I have the same problem as described by @darkgrayknight when I use the debugging functionality in the VSCode extension. In addition, this is the underlying error:

```text
Error: Cannot find module 'vite'
Require stack:
- e:\repos\project\vite.config.js
- E:\repos\project\node_modules\.pnpm\vite@2.9.12\node_modules\vite\dist\node\chunks\dep-8f5c9290.js
- E:\repos\project\node_modules\.pnpm\vite@2.9.12\node_modules\vite\dist\node\index.js
    at Function.Module._resolveFilename (e:\repos\project\lib\internal\modules\cjs\loader.js:933:15)
    at Function.Module._load (e:\repos\project\lib\internal\modules\cjs\loader.js:778:27)
    at Module.require (e:\repos\project\lib\internal\modules\cjs\loader.js:1005:19)
    at require (e:\repos\project\lib\internal\modules\cjs\helpers.js:102:18)
    at Object.<anonymous> (e:\repos\project\vite.config.js:25:19)
    at Module._compile (e:\repos\project\lib\internal\modules\cjs\loader.js:1105:14)
    at Object.require.extensions.<computed> [as .js] (E:\repos\project\node_modules\.pnpm\vite@2.9.12\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:61963:20)
    at Module.load (e:\repos\project\lib\internal\modules\cjs\loader.js:981:32)
    at Function.Module._load (e:\repos\project\lib\internal\modules\cjs\loader.js:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {code: 'MODULE_NOT_FOUND', requireStack: Array(3), stack: 'Error: Cannot find module 'vite'
Require stac…re (node:internal/modules/cjs/loader:1005:19)', message: 'Cannot find module 'vite'
Require stack:
- e…@2.9.12\node_modules\vite\dist\node\index.js'}
```

Maybe you can look into this and open the issue in the meanwhile @zxch3n ?
Thank you!

**Comment by zxch3n** [comment]
@itpropro I publish a new version to pre-release just now, v0.2.18. Can you check whether this is still happening?

**Comment by itpropro** [comment]
> @itpropro I publish a new version to pre-release just now, v0.2.18. Can you check whether this is still happening?

All my problems are fixed since 2.16/17, thanks for the effort :)
